version: '3.8'

services:
  time-tracker:
    build: ./server
    container_name: universal-time-tracker
    ports:
      - "9000:9000"
    volumes:
      # Persistent data storage
      - ./data:/app/data
      # Development: Mount source code for instant changes
      - ./server/src:/app/src
      # Mount prompts directory for AI customization
      - ./server/prompts:/app/prompts
    environment:
      - PORT=9000
      - DEBUG=true
      - DATABASE_PATH=/app/data/timetracker.db
      - TZ=America/New_York
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - TIME_TRACKER_USER_ID=${USER:-jdehart}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  time-tracker-data:
    driver: local
